name: urclimask
channels:
  - conda-forge
dependencies:
  - dask
  - geopandas
  - icecream
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - python
  - shapely
  - xarray
  - yaml
  - cf-xarray
  - papermill
  - scikit-image
  - netcdf4
  - tqdm
